spring.application.name=orchestrator-service
server.port=8080
server.address=0.0.0.0

app.user-service-url=http://192.168.1.11:8081
app.tour-service-url=http://192.168.1.12:8082
app.booking-service-url=http://192.168.1.13:8083
app.payment-service-url=http://192.168.1.14:8084
